[package]
name = "roxi-tests"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { workspace = true }
dirs = { version = "5.0" }
rand = { version = "0.8" }
regex = { version = "1.11" }
roxi-lib = { path = "../roxi-lib" }
roxi-client = { path = "../roxi-client" }
roxi-proto = { path = "../roxi-proto" }
roxi-server = { path = "../roxi-server" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber =  { workspace = true }
