[package]
name = "roxi-tests"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { workspace = true }
regex = { version = "1.11" }
roxi-server = { path = "../roxi-server" }
roxi-lib = { path = "../roxi-lib" }
roxi-client = { path = "../roxi-client" }
tokio = { workspace = true }
tracing-subscriber = "0.3.18"
