[package]
name = "roxi-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Roxi Server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { workspace = true }
bytes = { version = "1" }
ring = { version = "0.17" }
roxi-client = { path = "../roxi-client" }
roxi-lib = { path = "../roxi-lib" }
roxi-proto = { path = "../roxi-proto" }
serde = { workspace = true }
serde_yaml = { version = "0.9" }
thiserror = { workspace = true }
tokio = { workspace = true }
tun = { version = "0.6" }
tracing = { workspace = true }

[[bin]]
name = "roxi_server"
path = "src/bin/main.rs"

[lib]
name = "roxi_server"
path = "src/lib.rs"
