[package]
name = "roxi-cli"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Roxi CLI"

[dependencies]
actix-web = { version = "4", default-features = false, features = ["macros"] }
anyhow = { workspace = true }
clap = { features = ["derive", "env"], workspace = true }
colorful = "0.2.2"
forc-tracing = { version = "0.31", default-features = false }
forc-util = { version = "0.35.0" }
humantime = "2.1.0"
hyper-rustls = { version = "0.23", features = ["http2"] }
indicatif = "0.17"
owo-colors = "1.3.0"
rand = "0.8"
roxi-client = { path = "../roxi-client" }
roxi-lib = { path = "../roxi-lib" }
roxi-server = { path = "../roxi-server" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.4.0"
tokio = { features = ["macros", "rt-multi-thread", "process"], workspace = true }
tracing = { workspace = true }
walkdir = "2"
whoami = "1.4"

[[bin]]
name = "roxi-cli"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"
name = "roxi_cli"
