[package]
name = "roxi-proto"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Roxi Server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { workspace = true }
bincode = { version = "1" }
boringtun = { version = "0.5" }
libp2p = { version = "0.52" }
ring = { version = "0.17" }
roxi-lib = { path = "../roxi-lib" }
serde = { workspace = true }
strum = { version = "0.26", features = ["derive"] }
strum_macros = { version = "0.26" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tun = { version = "0.6" }

[lib]
name = "roxi_proto"
path = "src/lib.rs"
