name: CI

on: [push, pull_request]

env:
  RUSTC_VERSION: 1.81.0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  cargo-toml-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - name: Setup binstall
        uses: taiki-e/install-action@cargo-binstall
      - name: Install Cargo.toml linter
        run: cargo binstall --no-confirm cargo-sort
      - name: Run Cargo.toml sort check
        run: cargo sort --check

  cargo-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: rustfmt
      - name: Run cargo fmt check
        run: cargo fmt --all -- --check

  cargo-clippy-no-default-features:
    runs-on: ubuntu-latest
    needs:
      - cargo-toml-fmt-check
      - cargo-fmt-check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy
      - name: Run cargo clippy without default features
        run: cargo clippy --locked --no-default-features -- -D warnings

  cargo-clippy-all-features-all-targets:
    runs-on: ubuntu-latest
    needs:
      - cargo-toml-fmt-check
      - cargo-fmt-check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy
      - name: Run cargo clippy with all features and targets
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

  build-and-test:
    runs-on: ubuntu-latest
    needs:
      - cargo-clippy-all-features-all-targets
      - cargo-clippy-no-default-features
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross_image: x86_64-linux-gnu
  #        - os: ubuntu-latest
  #          platform: linux-arm
  #          target: aarch64-unknown-linux-gnu
  #          cross_image: aarch64-linux-gnu
  #        - os: ubuntu-latest
  #          platform: darwin
  #          target: x86_64-apple-darwin
  #        - os: macos-latest
  #          platform: darwin-arm
  #          target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          target: ${{ matrix.platform }}

      - name: Install cross
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cross
          cache-key: ${{ matrix.job.target }}

      - name: Install deps
        run: |
          sh scripts/ci/cargo-build-deps.sh
      - name: Build
        run: cargo build --target ${{ matrix.job.target }} --release

      - name: Test
        run: cargo test --target ${{ matrix.job.target }} -- --test-threads=1
